# Link to the dataset :
https://www.kaggle.com/datasets/anmatngu/2024-lol-championship-player-stats-and-swiss-stage

# Imports

In [1]:
import pandas as pd

# Reading and consultation

In [4]:
df = pd.read_csv('player_statistics_cleaned_final.csv')

In [5]:
df.isnull().sum()

TeamName         0
PlayerName       0
Position         0
Games            0
Win rate         0
KDA              0
Avg kills        0
Avg deaths       0
Avg assists      0
CSPerMin         0
GoldPerMin       0
KP%              0
DamagePercent    0
DPM              0
VSPM             0
Avg WPM          0
Avg WCPM         0
Avg VWPM         0
GD@15            0
CSD@15           0
XPD@15           0
FB %             0
FB Victim        0
Penta Kills      0
Solo Kills       0
Country          0
FlashKeybind     0
dtype: int64

In [6]:
df.head()

,TeamName,PlayerName,Position,Games,Win rate,KDA,Avg kills,Avg deaths,Avg assists,CSPerMin,...,Avg VWPM,GD@15,CSD@15,XPD@15,FB %,FB Victim,Penta Kills,Solo Kills,Country,FlashKeybind
0,Top Esports,369,Top,8,0.500,3.1,2.5,2.4,4.9,7.6,...,0.13,322,5,424,0.000,0.25,0,2,China,D
1,Dplus KIA,aiming,Adc,9,0.333,4.8,5.0,2.0,4.7,10.1,...,0.10,-112,1,97,0.333,0.00,0,2,South Korea,F
2,MAD Lions KOI,alvaro,Support,5,0.200,1.5,0.2,4.4,6.2,1.2,...,0.49,-3,2,-256,0.000,0.60,0,-,Spain,D
3,Team Liquid,apa,Mid,10,0.500,2.4,3.5,3.2,4.2,8.7,...,0.18,278,2,216,0.400,0.00,0,3,United States,D
4,PSG Talon,azhi,Top,5,0.200,2.3,2.2,3.0,4.8,7.5,...,0.18,-311,-10,-168,0.200,0.00,0,-,Taiwan,D

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TeamName       81 non-null     object
 1   PlayerName     81 non-null     object
 2   Position       81 non-null     object
 3   Games          81 non-null     int64
 4   Win rate       81 non-null     float64
 5   KDA            81 non-null     float64
 6   Avg kills      81 non-null     float64
 7   Avg deaths     81 non-null     float64
 8   Avg assists    81 non-null     float64
 9   CSPerMin       81 non-null     float64
 10  GoldPerMin     81 non-null     int64
 11  KP%            81 non-null     float64
 12  DamagePercent  81 non-null     float64
 13  DPM            81 non-null     int64
 14  VSPM           81 non-null     float64
 15  Avg WPM        81 non-null     float64
 16  Avg WCPM       81 non-null     float64
 17  Avg VWPM       81 non-null     float64
 18  GD@15          81 non-null     int64
 19  CSD@15         81 non-null     int64
 20  XPD@15         81 non-null     int64
 21  FB %           81 non-null     float64
 22  FB Victim      81 non-null     float64
 23  Penta Kills    81 non-null     int64
 24  Solo Kills     81 non-null     object
 25  Country        81 non-null     object
 26  FlashKeybind   81 non-null     object
dtypes: float64(14), int64(7), object(6)
memory usage: 17.2+ KB